name: OneAP CI Test Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          TM_API_KEY: ${{ secrets.TESTMANAGER_API_KEY }}
          TM_BASE_URL: ${{ secrets.TESTMANAGER_URL }}/api
          TM_PROJECT_ID: ${{ secrets.TESTMANAGER_PROJECT_ID }}
        run: npx cypress run
